BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "user_ids" (
	"id"	INTEGER NOT NULL,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "data" (
	"id"	INTEGER NOT NULL,
	"coin_name"	TEXT NOT NULL,
	"price"	REAL NOT NULL,
	"count"	REAL NOT NULL,
	"dt"	DATETIME NOT NULL,
	"dt_out"	DATETIME NOT NULL DEFAULT '1999-01-01 00:00:00.000000',
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
