BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "user_ids" (
	"id"	INTEGER NOT NULL,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "data" (
	"id"	INTEGER NOT NULL,
	"coin_name"	TEXT NOT NULL,
	"price"	REAL NOT NULL,
	"count"	REAL NOT NULL,
	"dt"	DATETIME NOT NULL,
	"timer"	DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00.000000',
	"in_range"	NUMERIC NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "current_price" (
	"id"	INTEGER,
	"coin_name"	TEXT,
	"price"	REAL NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
